# Generated by Django 5.0.2 on 2024-02-28 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Computer', 'คอมพิวเตอร์'), ('Laptop', 'โน๊ตบุ๊ค'), ('Computer Accessory', 'อุปกรณ์คอมพิวเตอร์'), ('Speaker', 'ลำโพง')], max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image1', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(blank=True, upload_to='product_images/')),
                ('image3', models.ImageField(blank=True, upload_to='product_images/')),
            ],
        ),
    ]
